### ISSUE TITLE
[Crash] On Server start up

### ISSUE THREAD

**Issue by logixcraft** [Dremoline/PortableMobs#1]
**Version info**
Minecraft 1.18.2
Portable Mobs 1.1.0

**Steps to reproduce**
updated supermartijn642core & supermartijn642config > updated portable mobs - Server start

**Crash report (~/logs/latest.log)** 
[crash-2022-07-13_12.37.42-fml.txt](https://github.com/Dremoline/PortableMobs/files/9104381/crash-2022-07-13_12.37.42-fml.txt)

**Comment by SuperMartijn642** [comment]
I fixed it now with 1ef1ba4879752c1631e8b5fd34e0b45440c11825. Up to @Dremoline to release an update.

**Comment by SuperMartijn642** [comment]
Fixed now in Portable Mobs 1.1.0a for 1.18.
Thank you for reporting the issue!
