### ISSUE TITLE
[Crash] fabric, 1.20.2

### ISSUE THREAD

**Issue by hellozyemlya** [Dremoline/PortableMobs#10]
**Version info**
Minecraft 1.20.2
Portable Mobs 1.2.0 for 1.20

**Steps to reproduce**
Just start a game.
**Crash report (~/logs/latest.log)** 
[mclo.gs link](https://mclo.gs/ri4qk3W)

**Comment by hellozyemlya** [comment]
@Dremoline seems like CriterionRegistry from fabric-object-builder-api-v1 is removed and deprecated in latest fabric...

**Comment by Dremoline** [comment]
Hey,
Should be fixed in the new update.
