### ISSUE TITLE
[Crash] CTD when capturing a Priest Villager

### ISSUE THREAD

**Issue by kezmodius** [Dremoline/PortableMobs#11]
**Version Info**
Minecraft 1.20.1
Portable Mobs portablemobs-1.2.0-forge-mc1.20.jar

**Steps to reproduce**
Click a cage on an Iron's Spells Priest (villager type from Iron's Spells and Spellbooks:irons_spellbooks-1.20.1-2.2.1.jar)
Hard crash to desktop

When logged back in Priest was in the cage and did not cause an issue when released.

**Crash report (~/logs/latest.log)** 
https://pastebin.com/rtXLiy8w
Client log. Playing on my server but server was totally unaffected (nothing about it in the log).
Link due to expire by 6/2/24

**Comment by SuperMartijn642** [comment]
It seems the pastebin website is down. Could you share the log through http://gist.github.com?

**Comment by kezmodius** [comment]
https://gist.github.com/kezmodius/305369e37c49da5cb2d613c2afd25717
Here it is!

**Comment by SuperMartijn642** [comment]
This appears to be an error on Iron's Spells 'n Spellbooks' side. Could you report the issue to them?

**Comment by kezmodius** [comment]
Ok. Will do.
