### ISSUE TITLE
[Crash] 1.20.1 Multiplayer client crash while rendering mob.

### ISSUE THREAD

**Issue by SociallyAwkrd** [Dremoline/PortableMobs#14]
**Version info**
Minecraft 1.20.1
Portable Mobs 1.2.0-forge-mc-s.20

**Steps to reproduce**
Install portable mobs, install SWEM mod. Log onto multiplayer server, capture SWEM horse, try and release swem horse. Client side crash.

**Crash report (~/logs/latest.log)** 

[crash-2024-06-28_01.10.16-client.txt](https://github.com/user-attachments/files/16022175/crash-2024-06-28_01.10.16-client.txt)

**Comment by Dremoline** [comment]
I've looked at the crashreport and it seems to be an issue on the side of the SWEM mod. Please report the issue to them.
