### ISSUE TITLE
[Crash] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [Dremoline/PortableMobs#2]
Minecraft 1.19
Forge 41.0.94+
supermartijn642configlib-1.1.6b-forge-mc1.19
supermartijn642corelib-1.0.19-forge-mc1.19
portablemobs-1.1.0-forge-mc1.19

java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ModelBakeEvent

[crashlog](https://github.com/Dremoline/PortableMobs/files/9126995/crash-2022-07-17_13.27.25-fml.txt)

**Comment by SuperMartijn642** [comment]
I updated things to Forge 41.0.94 now with 5eb8ea5781108e18772ecd8d95cad74822e35113. Up to @Dremoline to release an update.

**Comment by SuperMartijn642** [comment]
Fixed now in Portable Mobs 1.1.0a for 1.19.
Thank you for reporting the issue!

**Comment by Baggytrousers27** [comment]
ºvº
