### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by mmohebpoor** [Dremoline/PortableMobs#3]
Hi,

Please update the mod to work with the latest SuperMartijn642's Core Lib update!
I use Chunk Loaders and SImple Magnets which also rely on the Core Lib, they have all been updated, however, since PortableMobs relies on an older version of the lib, I can't update Chunk Loaders and Simple Magnets until PortableMobs has been updated. Thanks for making and updating this simple but useful mod! :)

![image](https://user-images.githubusercontent.com/41317458/211147013-a254a373-af55-42d9-b3e8-ff3fdfb8b364.png)

**Comment by MC-Valdreth** [comment]
I'm having the same issue with the newest version of SuperMartijn642's Core Lib. After updating all of my mods I see the following in my [latest.log](https://pastebin.com/dGbpaRXQ)

[20:57:20] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'supermartijn642corelib', Requested by: 'portablemobs', Expected range: '[1.0.19,1.1.0)', Actual version: '1.1.1'

**Comment by Lothloriian** [comment]
I have had the same issue. I wrote it on the core lib page, but I think this is  better location.  It seems to be specific to Portable Mobs, as additional lanterns seems to launch okay.

**Comment by SuperMartijn642** [comment]
Portable Mobs' dependency on my core library is simply set to only accept versions below 1.1.0. This is intentional as version 1.1.0 of my core library has many breaking changes.
@Dremoline and I are both quite busy and we have to find a time where we're both available, so updating takes a bit.

> ... as additional lanterns seems to launch okay.

All my own mods, including Additional Lanterns, were updated alongside the update for my core library, so those should work fine.

**Comment by Lothloriian** [comment]
Hey no worries, I just wanted to report it.  I'm in the middle of a move right now anyways, so I dont have a lot of time myself, I understand your struggle.

**Comment by PANDITA990** [comment]
> Hola,
> 
> ¡Actualice el mod para que funcione con la última actualización Core Lib de SuperMartijn642! Utilizo Chunk Loaders y SImple Magnets que también se basan en Core Lib, todos se han actualizado, sin embargo, dado que PortableMobs se basa en una versión anterior de lib, no puedo actualizar Chunk Loaders y Simple Magnets hasta que PortableMobs se haya actualizado. ¡Gracias por crear y actualizar este mod simple pero útil! :)
> 
> ![imagen](https://user-images.githubusercontent.com/41317458/211147013-a254a373-af55-42d9-b3e8-ff3fdfb8b364.png)

I had the same problem, I fixed it by opening the mod with winrar, then META-INF folder, mods.toml file. and edit the final part of versionRange="[1.0.19,1.1.0)" to versionRange="[1.0.19,)", save and you're done. Now the mod opens normally with the most recent version of supermartijn642corelib

**Comment by SuperMartijn642** [comment]
> edit the final part of versionRange="[1.0.19,1.1.0)" to versionRange="[1.0.19,)"

Yeah that's not a good idea. Code for <1.1.0 is not compatible with >=1.1.0, so even though the mod might load initially, that will lead to unexpected crashes once playing. The version limit is there for a reason.

**Comment by PANDITA990** [comment]
> > edite la parte final de versionRange="[1.0.19,1.1.0)" a versionRange="[1.0.19,)"
> 
> Sí, eso no es una buena idea. El código para <1.1.0 no es compatible con >=1.1.0, por lo que, aunque el mod se carga inicialmente, provocará bloqueos inesperados una vez que se reproduzca. El límite de versiones está ahí por una razón.

I've been using it like this since supermartijn642corelib was updated and it hasn't given me any type of blockage and it works 100% for me

**Comment by Dremoline** [comment]
Hey, it's been updated in 1.1.2!
