### ISSUE TITLE
[Bug] Certain mobs can't be captured

### ISSUE THREAD

**Issue by Fingernailsss** [Dremoline/PortableMobs#6]
**Version info**
Minecraft (1.19.2)
Portable Mobs (1.1.1-forge-mc1.19)

**Describe the bug**
Certain mobs can't be captured, even with a master cell
**To Reproduce**
1. Download 'Seeds' (https://www.curseforge.com/minecraft/mc-mods/seeds)
2. Spawn a Bad Grass
3. Successfully capture the Bad grass
4. Spawn a Mud golem
5. Attempt to capture the Mud golem
6. See error

**Screenshots**
None

**Comment by SuperMartijn642** [comment]
Thanks for the report! I usually help Dremoline with all the programming parts, so we have to find a time when we're both available. As we're both quite busy, it might be a bit before we get to this issue 😅

**Comment by Dremoline** [comment]
Hey, thanks for reporting. Could you provide the crashreport? That way it will be easier to spot the problem.

**Comment by Fingernailsss** [comment]
there is no crash. it just... doesn't work. nothing happens
