### ISSUE TITLE
[Bug] Most mobs that can be interacted with, can't be captured

### ISSUE THREAD

**Issue by Denkata-Iliev** [Dremoline/PortableMobs#7]
**Version info**
Minecraft 1.20.1 (Fabric)
Portable Mobs 1.1.2

**Describe the bug**
Any mobs that can be interacted with, can't be captured. I've tried capturing villagers, donkeys, horses, llamas and wandering traders. I also tried to capture a camel, and it worked for some reason. (Also see [this reddit thread describing the same thing](https://www.reddit.com/r/feedthebeast/comments/14k6pwc/portable_mobs_not_working_on_villagers/)).

**To Reproduce**
1. Intall the mod
2. Go into a world
3. Get a basic or a master capture cell
4. Try to capture a villager, a horse, a donkey, a llama or a wander trader
5. Nothing happens.

**Screenshots**
I don't have screenshots, but here's a quick 10 sec video of the bug

https://github.com/Dremoline/PortableMobs/assets/45120338/e2c608f7-061e-4187-a086-42d4a138246c

**Comment by Dremoline** [comment]
Hello, 
It should be fixed in the new update. Thanks for the clear report of the issue! It made it a lot easier to fix it.
