### ISSUE TITLE
[Feature] Trap based capture as a block

### ISSUE THREAD

**Issue by Darkmega18** [Dremoline/PortableMobs#8]
The capture cells looks like they could be used as blocks, but it's used from the hand. 

Apparently some versions back untamed wilds added a block which I saw in some older MC videos which acted like a pressure plate and when a mob stepped onto it the box would shut closed and capture the mob into a box and you could mine the box and place it somewhere else to deploy the mob again afterwards.

I'm thinking, if you make your cages placeable you could make a similar mechanic to this. where it's made placeable and if the cage gets redstone (you put a pressure plate on it) cage will steal the mob standing on top of it and fill itself. The mob cage can then be mined and moved and will render the mob inside the cage when placed again and a further redstone signal again will deploy the mob onto it's top.

Either or both modes of capture should be configurable to be allowed or not. So you can directly capture, or remotely capture like a trap of sorts or have either mode depending on pack desires.

**Comment by Dremoline** [comment]
Hey,
It's a fun idea, but I'm not looking to add features to the mod atm. Perhaps in the future. 
But thanks for the feedback.

**Comment by Darkmega18** [comment]
:<
